;;; ============================================================
;;;  IJCAD用 AutoLISP (QSBCコマンド) - PowerShell/WPF UI版
;;;  ブロックエディタ(BEDIT)を開かずに、選択したブロックの内部にある
;;;  すべての線・図形の画層・線種・色・線の太さを一括変更する
;;;  UIはマテリアルデザイン風(アプリバー/カード/チップ/円形スウォッチ)
;;;  ※通常ブロックを対象に想定。ダイナミックブロックは未検証。
;;; ============================================================

(vl-load-com)

;; --- WScript.ShellでPowerShellを同期起動 -----------------------------
(defun qsbc-run-ps1 (ps1Path inPath outPath / wsh cmd)
  (setq wsh (vlax-create-object "WScript.Shell"))
  (setq cmd (strcat
              "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "
              "\"" ps1Path "\" -InputPath \"" inPath "\" -OutputPath \"" outPath "\""
            ))
  (vlax-invoke-method wsh 'Run cmd 0 :vlax-true)
  (vlax-release-object wsh)
  (princ)
)

;; --- 埋め込みPowerShell(WPF)スクリプトの書き出し ----------------------
(defun qsbc-write-ps1-script (path / fn)
  (setq fn (open path "w"))
  (write-line "[CmdletBinding()]" fn)
  (write-line "param(" fn)
  (write-line "    [Parameter(Mandatory=$true)][string]$InputPath," fn)
  (write-line "    [Parameter(Mandatory=$true)][string]$OutputPath" fn)
  (write-line ")" fn)
  (write-line "Add-Type -AssemblyName PresentationFramework" fn)
  (write-line "Add-Type -AssemblyName PresentationCore" fn)
  (write-line "Add-Type -AssemblyName WindowsBase" fn)
  (write-line "" fn)
  (write-line "function Read-InputData ($path) {" fn)
  (write-line "    $data = @{ Layers = @(); Ltypes = @(); Colors = @(); Lwts = @(); EntCount = 0; BlkCount = 0 }" fn)
  (write-line "    $cur = $null" fn)
  (write-line "    if (Test-Path -LiteralPath $path) {" fn)
  (write-line "        $lines = Get-Content -LiteralPath $path -Encoding Default" fn)
  (write-line "        foreach ($line in $lines) {" fn)
  (write-line "            if ($line -match '^###(.+)###$') {" fn)
  (write-line "                $cur = $Matches[1]" fn)
  (write-line "            } elseif ($cur -eq 'LAYERS' -and $line -ne '') {" fn)
  (write-line "                $data.Layers += $line" fn)
  (write-line "            } elseif ($cur -eq 'LTYPES' -and $line -ne '') {" fn)
  (write-line "                $data.Ltypes += $line" fn)
  (write-line "            } elseif ($cur -eq 'COLORS' -and $line -ne '') {" fn)
  (write-line "                $data.Colors += $line" fn)
  (write-line "            } elseif ($cur -eq 'LWTS' -and $line -ne '') {" fn)
  (write-line "                $data.Lwts += $line" fn)
  (write-line "            } elseif ($cur -eq 'ENTCOUNT' -and $line -ne '') {" fn)
  (write-line "                $data.EntCount = $line" fn)
  (write-line "            } elseif ($cur -eq 'BLKCOUNT' -and $line -ne '') {" fn)
  (write-line "                $data.BlkCount = $line" fn)
  (write-line "            }" fn)
  (write-line "        }" fn)
  (write-line "    }" fn)
  (write-line "    return $data" fn)
  (write-line "}" fn)
  (write-line "" fn)
  (write-line "function Get-AciRgb ([int]$idx) {" fn)
  (write-line "    switch ($idx) {" fn)
  (write-line "        1  { return @(255,0,0) }" fn)
  (write-line "        2  { return @(255,255,0) }" fn)
  (write-line "        3  { return @(0,255,0) }" fn)
  (write-line "        4  { return @(0,255,255) }" fn)
  (write-line "        5  { return @(0,0,255) }" fn)
  (write-line "        6  { return @(255,0,255) }" fn)
  (write-line "        7  { return @(255,255,255) }" fn)
  (write-line "        8  { return @(65,65,65) }" fn)
  (write-line "        9  { return @(128,128,128) }" fn)
  (write-line "        default {" fn)
  (write-line "            if ($idx -ge 250) {" fn)
  (write-line "                $g = 51 + [math]::Round((($idx - 250) / 5.0) * 204)" fn)
  (write-line "                return @($g,$g,$g)" fn)
  (write-line "            } else {" fn)
  (write-line "                $hue = (($idx - 10) % 30) * 12" fn)
  (write-line "                $light = 0.35 + ((($idx - 10) % 6) * 0.1)" fn)
  (write-line "                $h = $hue / 60.0" fn)
  (write-line "                $c = (1 - [math]::Abs((2 * $light) - 1))" fn)
  (write-line "                $x = $c * (1 - [math]::Abs(($h % 2) - 1))" fn)
  (write-line "                $m = $light - ($c / 2)" fn)
  (write-line "                switch ([int][math]::Floor($h)) {" fn)
  (write-line "                    0 { $r = $c; $g = $x; $b = 0 }" fn)
  (write-line "                    1 { $r = $x; $g = $c; $b = 0 }" fn)
  (write-line "                    2 { $r = 0; $g = $c; $b = $x }" fn)
  (write-line "                    3 { $r = 0; $g = $x; $b = $c }" fn)
  (write-line "                    4 { $r = $x; $g = 0; $b = $c }" fn)
  (write-line "                    default { $r = $c; $g = 0; $b = $x }" fn)
  (write-line "                }" fn)
  (write-line "                return @([int](($r + $m) * 255), [int](($g + $m) * 255), [int](($b + $m) * 255))" fn)
  (write-line "            }" fn)
  (write-line "        }" fn)
  (write-line "    }" fn)
  (write-line "}" fn)
  (write-line "" fn)
  (write-line "$inputData = Read-InputData -path $InputPath" fn)
  (write-line "" fn)
  (write-line "$xaml = @'" fn)
  (write-line "<Window xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\"" fn)
  (write-line "        xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\"" fn)
  (write-line "        Title=\"ブロック内部一括編集\" Height=\"800\" Width=\"1000\"" fn)
  (write-line "        WindowStartupLocation=\"CenterScreen\" ResizeMode=\"NoResize\"" fn)
  (write-line "        Background=\"#FFFAFAFA\" FontFamily=\"Roboto, Yu Gothic UI, Segoe UI\">" fn)
  (write-line "  <Window.Resources>" fn)
  (write-line "    <Style x:Key=\"ChipButton\" TargetType=\"Button\">" fn)
  (write-line "      <Setter Property=\"Background\" Value=\"#FFEEEEEE\"/>" fn)
  (write-line "      <Setter Property=\"Foreground\" Value=\"#FF212121\"/>" fn)
  (write-line "      <Setter Property=\"FontSize\" Value=\"13\"/>" fn)
  (write-line "      <Setter Property=\"BorderThickness\" Value=\"0\"/>" fn)
  (write-line "      <Setter Property=\"Padding\" Value=\"14,7\"/>" fn)
  (write-line "      <Setter Property=\"Margin\" Value=\"0,0,8,8\"/>" fn)
  (write-line "      <Setter Property=\"Cursor\" Value=\"Hand\"/>" fn)
  (write-line "      <Setter Property=\"Template\">" fn)
  (write-line "        <Setter.Value>" fn)
  (write-line "          <ControlTemplate TargetType=\"Button\">" fn)
  (write-line "            <Border x:Name=\"bd\" Background=\"{TemplateBinding Background}\" CornerRadius=\"16\" Padding=\"{TemplateBinding Padding}\">" fn)
  (write-line "              <ContentPresenter HorizontalAlignment=\"Center\" VerticalAlignment=\"Center\"/>" fn)
  (write-line "            </Border>" fn)
  (write-line "            <ControlTemplate.Triggers>" fn)
  (write-line "              <Trigger Property=\"IsMouseOver\" Value=\"True\">" fn)
  (write-line "                <Setter TargetName=\"bd\" Property=\"Background\" Value=\"#FFE0E0E0\"/>" fn)
  (write-line "              </Trigger>" fn)
  (write-line "            </ControlTemplate.Triggers>" fn)
  (write-line "          </ControlTemplate>" fn)
  (write-line "        </Setter.Value>" fn)
  (write-line "      </Setter>" fn)
  (write-line "    </Style>" fn)
  (write-line "    <Style x:Key=\"SwatchButton\" TargetType=\"Button\">" fn)
  (write-line "      <Setter Property=\"Width\" Value=\"24\"/>" fn)
  (write-line "      <Setter Property=\"Height\" Value=\"24\"/>" fn)
  (write-line "      <Setter Property=\"Margin\" Value=\"4\"/>" fn)
  (write-line "      <Setter Property=\"BorderThickness\" Value=\"0\"/>" fn)
  (write-line "      <Setter Property=\"Cursor\" Value=\"Hand\"/>" fn)
  (write-line "      <Setter Property=\"Template\">" fn)
  (write-line "        <Setter.Value>" fn)
  (write-line "          <ControlTemplate TargetType=\"Button\">" fn)
  (write-line "            <Border x:Name=\"bd\" Background=\"{TemplateBinding Background}\" CornerRadius=\"12\" BorderBrush=\"Transparent\" BorderThickness=\"2\"/>" fn)
  (write-line "            <ControlTemplate.Triggers>" fn)
  (write-line "              <Trigger Property=\"IsMouseOver\" Value=\"True\">" fn)
  (write-line "                <Setter TargetName=\"bd\" Property=\"BorderBrush\" Value=\"#FF3F51B5\"/>" fn)
  (write-line "              </Trigger>" fn)
  (write-line "            </ControlTemplate.Triggers>" fn)
  (write-line "          </ControlTemplate>" fn)
  (write-line "        </Setter.Value>" fn)
  (write-line "      </Setter>" fn)
  (write-line "    </Style>" fn)
  (write-line "    <Style x:Key=\"FlatTextButton\" TargetType=\"Button\">" fn)
  (write-line "      <Setter Property=\"Background\" Value=\"Transparent\"/>" fn)
  (write-line "      <Setter Property=\"FontWeight\" Value=\"Bold\"/>" fn)
  (write-line "      <Setter Property=\"FontSize\" Value=\"14\"/>" fn)
  (write-line "      <Setter Property=\"BorderThickness\" Value=\"0\"/>" fn)
  (write-line "      <Setter Property=\"Padding\" Value=\"16,9\"/>" fn)
  (write-line "      <Setter Property=\"Cursor\" Value=\"Hand\"/>" fn)
  (write-line "      <Setter Property=\"Template\">" fn)
  (write-line "        <Setter.Value>" fn)
  (write-line "          <ControlTemplate TargetType=\"Button\">" fn)
  (write-line "            <Border x:Name=\"bd\" Background=\"{TemplateBinding Background}\" CornerRadius=\"4\" Padding=\"{TemplateBinding Padding}\">" fn)
  (write-line "              <ContentPresenter HorizontalAlignment=\"Center\" VerticalAlignment=\"Center\" TextElement.Foreground=\"{TemplateBinding Foreground}\"/>" fn)
  (write-line "            </Border>" fn)
  (write-line "            <ControlTemplate.Triggers>" fn)
  (write-line "              <Trigger Property=\"IsMouseOver\" Value=\"True\">" fn)
  (write-line "                <Setter TargetName=\"bd\" Property=\"Background\" Value=\"#14000000\"/>" fn)
  (write-line "              </Trigger>" fn)
  (write-line "            </ControlTemplate.Triggers>" fn)
  (write-line "          </ControlTemplate>" fn)
  (write-line "        </Setter.Value>" fn)
  (write-line "      </Setter>" fn)
  (write-line "    </Style>" fn)
  (write-line "    <Style TargetType=\"ListBox\">" fn)
  (write-line "      <Setter Property=\"BorderThickness\" Value=\"0\"/>" fn)
  (write-line "      <Setter Property=\"Background\" Value=\"Transparent\"/>" fn)
  (write-line "    </Style>" fn)
  (write-line "    <Style TargetType=\"ListBoxItem\">" fn)
  (write-line "      <Setter Property=\"Padding\" Value=\"12,10\"/>" fn)
  (write-line "      <Setter Property=\"FontSize\" Value=\"14\"/>" fn)
  (write-line "      <Setter Property=\"Template\">" fn)
  (write-line "        <Setter.Value>" fn)
  (write-line "          <ControlTemplate TargetType=\"ListBoxItem\">" fn)
  (write-line "            <Border x:Name=\"bd\" Background=\"Transparent\" Padding=\"{TemplateBinding Padding}\" BorderBrush=\"#FFEEEEEE\" BorderThickness=\"0,0,0,1\">" fn)
  (write-line "              <ContentPresenter/>" fn)
  (write-line "            </Border>" fn)
  (write-line "            <ControlTemplate.Triggers>" fn)
  (write-line "              <Trigger Property=\"IsSelected\" Value=\"True\">" fn)
  (write-line "                <Setter TargetName=\"bd\" Property=\"Background\" Value=\"#FFC5CAE9\"/>" fn)
  (write-line "              </Trigger>" fn)
  (write-line "              <Trigger Property=\"IsMouseOver\" Value=\"True\">" fn)
  (write-line "                <Setter TargetName=\"bd\" Property=\"Background\" Value=\"#FFF5F5F5\"/>" fn)
  (write-line "              </Trigger>" fn)
  (write-line "            </ControlTemplate.Triggers>" fn)
  (write-line "          </ControlTemplate>" fn)
  (write-line "        </Setter.Value>" fn)
  (write-line "      </Setter>" fn)
  (write-line "    </Style>" fn)
  (write-line "  </Window.Resources>" fn)
  (write-line "  <Grid>" fn)
  (write-line "    <Grid.RowDefinitions>" fn)
  (write-line "      <RowDefinition Height=\"56\"/>" fn)
  (write-line "      <RowDefinition Height=\"*\"/>" fn)
  (write-line "    </Grid.RowDefinitions>" fn)
  (write-line "    <Border Grid.Row=\"0\" Background=\"#FF3F51B5\">" fn)
  (write-line "      <Border.Effect>" fn)
  (write-line "        <DropShadowEffect BlurRadius=\"8\" ShadowDepth=\"2\" Direction=\"270\" Opacity=\"0.3\" Color=\"#FF000000\"/>" fn)
  (write-line "      </Border.Effect>" fn)
  (write-line "      <TextBlock Text=\"ブロック内部一括編集\" Foreground=\"White\" FontSize=\"16\" FontWeight=\"Bold\" VerticalAlignment=\"Center\" Margin=\"20,0,0,0\"/>" fn)
  (write-line "    </Border>" fn)
  (write-line "    <Grid Grid.Row=\"1\" Margin=\"20,16,20,20\">" fn)
  (write-line "      <Grid.RowDefinitions>" fn)
  (write-line "        <RowDefinition Height=\"Auto\"/>" fn)
  (write-line "        <RowDefinition Height=\"*\"/>" fn)
  (write-line "        <RowDefinition Height=\"Auto\"/>" fn)
  (write-line "      </Grid.RowDefinitions>" fn)
  (write-line "      <Grid.ColumnDefinitions>" fn)
  (write-line "        <ColumnDefinition Width=\"*\"/>" fn)
  (write-line "        <ColumnDefinition Width=\"28\"/>" fn)
  (write-line "        <ColumnDefinition Width=\"*\"/>" fn)
  (write-line "      </Grid.ColumnDefinitions>" fn)
  (write-line "      <TextBlock Grid.Row=\"0\" Grid.Column=\"0\" Grid.ColumnSpan=\"3\" Name=\"InfoText\" FontSize=\"13\" FontWeight=\"SemiBold\" Foreground=\"#FF424242\" Margin=\"0,0,0,16\" TextWrapping=\"Wrap\"/>" fn)
  (write-line "      <Grid Grid.Row=\"1\" Grid.Column=\"0\">" fn)
  (write-line "        <Grid.RowDefinitions>" fn)
  (write-line "          <RowDefinition Height=\"Auto\"/>" fn)
  (write-line "          <RowDefinition Height=\"*\"/>" fn)
  (write-line "          <RowDefinition Height=\"Auto\"/>" fn)
  (write-line "          <RowDefinition Height=\"*\"/>" fn)
  (write-line "        </Grid.RowDefinitions>" fn)
  (write-line "        <StackPanel Grid.Row=\"0\" Margin=\"2,0,0,8\">" fn)
  (write-line "          <TextBlock Text=\"変更後の画層\" FontSize=\"12\" FontWeight=\"Bold\" Foreground=\"#FF3F51B5\"/>" fn)
  (write-line "          <TextBlock Name=\"CurrentLayersText\" FontSize=\"11\" Foreground=\"#FF9E9E9E\" Margin=\"0,2,0,0\" TextWrapping=\"Wrap\"/>" fn)
  (write-line "        </StackPanel>" fn)
  (write-line "        <Border Grid.Row=\"1\" Background=\"White\" CornerRadius=\"6\" Margin=\"0,0,0,14\">" fn)
  (write-line "          <Border.Effect>" fn)
  (write-line "            <DropShadowEffect BlurRadius=\"6\" ShadowDepth=\"1\" Opacity=\"0.15\" Color=\"#FF000000\"/>" fn)
  (write-line "          </Border.Effect>" fn)
  (write-line "          <ListBox Name=\"LayerList\"/>" fn)
  (write-line "        </Border>" fn)
  (write-line "        <StackPanel Grid.Row=\"2\" Margin=\"2,0,0,8\">" fn)
  (write-line "          <TextBlock Text=\"変更後の線種\" FontSize=\"12\" FontWeight=\"Bold\" Foreground=\"#FF3F51B5\"/>" fn)
  (write-line "          <TextBlock Name=\"CurrentLtypesText\" FontSize=\"11\" Foreground=\"#FF9E9E9E\" Margin=\"0,2,0,0\" TextWrapping=\"Wrap\"/>" fn)
  (write-line "        </StackPanel>" fn)
  (write-line "        <Border Grid.Row=\"3\" Background=\"White\" CornerRadius=\"6\">" fn)
  (write-line "          <Border.Effect>" fn)
  (write-line "            <DropShadowEffect BlurRadius=\"6\" ShadowDepth=\"1\" Opacity=\"0.15\" Color=\"#FF000000\"/>" fn)
  (write-line "          </Border.Effect>" fn)
  (write-line "          <ListBox Name=\"LtypeList\"/>" fn)
  (write-line "        </Border>" fn)
  (write-line "      </Grid>" fn)
  (write-line "      <Grid Grid.Row=\"1\" Grid.Column=\"2\">" fn)
  (write-line "        <Grid.RowDefinitions>" fn)
  (write-line "          <RowDefinition Height=\"Auto\"/>" fn)
  (write-line "          <RowDefinition Height=\"Auto\"/>" fn)
  (write-line "          <RowDefinition Height=\"*\"/>" fn)
  (write-line "          <RowDefinition Height=\"Auto\"/>" fn)
  (write-line "          <RowDefinition Height=\"Auto\"/>" fn)
  (write-line "          <RowDefinition Height=\"Auto\"/>" fn)
  (write-line "        </Grid.RowDefinitions>" fn)
  (write-line "        <StackPanel Grid.Row=\"0\" Margin=\"2,0,0,8\">" fn)
  (write-line "          <TextBlock Text=\"変更後の色\" FontSize=\"12\" FontWeight=\"Bold\" Foreground=\"#FF3F51B5\"/>" fn)
  (write-line "          <TextBlock Name=\"CurrentColorsText\" FontSize=\"11\" Foreground=\"#FF9E9E9E\" Margin=\"0,2,0,0\" TextWrapping=\"Wrap\"/>" fn)
  (write-line "        </StackPanel>" fn)
  (write-line "        <StackPanel Grid.Row=\"1\" Name=\"QuickColorPanel\" Orientation=\"Horizontal\" Margin=\"0,0,0,8\"/>" fn)
  (write-line "        <Border Grid.Row=\"2\" Background=\"White\" CornerRadius=\"6\" Margin=\"0,0,0,10\">" fn)
  (write-line "          <Border.Effect>" fn)
  (write-line "            <DropShadowEffect BlurRadius=\"6\" ShadowDepth=\"1\" Opacity=\"0.15\" Color=\"#FF000000\"/>" fn)
  (write-line "          </Border.Effect>" fn)
  (write-line "          <ScrollViewer VerticalScrollBarVisibility=\"Auto\" Margin=\"6\">" fn)
  (write-line "            <WrapPanel Name=\"ColorWrap\"/>" fn)
  (write-line "          </ScrollViewer>" fn)
  (write-line "        </Border>" fn)
  (write-line "        <TextBlock Grid.Row=\"3\" Name=\"SelectedColorText\" FontSize=\"13\" FontWeight=\"SemiBold\" Foreground=\"#FF212121\" Margin=\"2,0,0,16\"/>" fn)
  (write-line "        <StackPanel Grid.Row=\"4\" Margin=\"2,0,0,8\">" fn)
  (write-line "          <TextBlock Text=\"変更後の線の太さ\" FontSize=\"12\" FontWeight=\"Bold\" Foreground=\"#FF3F51B5\"/>" fn)
  (write-line "          <TextBlock Name=\"CurrentLwtsText\" FontSize=\"11\" Foreground=\"#FF9E9E9E\" Margin=\"0,2,0,0\" TextWrapping=\"Wrap\"/>" fn)
  (write-line "        </StackPanel>" fn)
  (write-line "        <StackPanel Grid.Row=\"5\">" fn)
  (write-line "          <StackPanel Name=\"LineweightPanel\" Orientation=\"Horizontal\"/>" fn)
  (write-line "          <TextBlock Name=\"SelectedLineweightText\" FontSize=\"13\" FontWeight=\"SemiBold\" Foreground=\"#FF212121\" Margin=\"2,8,0,0\"/>" fn)
  (write-line "        </StackPanel>" fn)
  (write-line "      </Grid>" fn)
  (write-line "      <StackPanel Grid.Row=\"2\" Grid.Column=\"0\" Grid.ColumnSpan=\"3\" Orientation=\"Horizontal\" HorizontalAlignment=\"Right\" Margin=\"0,16,0,0\">" fn)
  (write-line "        <Button Name=\"CancelButton\" Content=\"キャンセル\" Style=\"{StaticResource FlatTextButton}\" Foreground=\"#FF757575\"/>" fn)
  (write-line "        <Button Name=\"ApplyButton\" Content=\"適用\" Style=\"{StaticResource FlatTextButton}\" Foreground=\"#FF3F51B5\"/>" fn)
  (write-line "      </StackPanel>" fn)
  (write-line "    </Grid>" fn)
  (write-line "  </Grid>" fn)
  (write-line "</Window>" fn)
  (write-line "'@" fn)
  (write-line "" fn)
  (write-line "$reader = [System.Xml.XmlNodeReader]::new([xml]$xaml)" fn)
  (write-line "$window = [Windows.Markup.XamlReader]::Load($reader)" fn)
  (write-line "" fn)
  (write-line "$infoText = $window.FindName('InfoText')" fn)
  (write-line "$currentLayersText = $window.FindName('CurrentLayersText')" fn)
  (write-line "$currentLtypesText = $window.FindName('CurrentLtypesText')" fn)
  (write-line "$currentColorsText = $window.FindName('CurrentColorsText')" fn)
  (write-line "$currentLwtsText = $window.FindName('CurrentLwtsText')" fn)
  (write-line "$layerList = $window.FindName('LayerList')" fn)
  (write-line "$ltypeList = $window.FindName('LtypeList')" fn)
  (write-line "$quickColorPanel = $window.FindName('QuickColorPanel')" fn)
  (write-line "$colorWrap = $window.FindName('ColorWrap')" fn)
  (write-line "$selectedColorText = $window.FindName('SelectedColorText')" fn)
  (write-line "$lineweightPanel = $window.FindName('LineweightPanel')" fn)
  (write-line "$selectedLineweightText = $window.FindName('SelectedLineweightText')" fn)
  (write-line "$applyButton = $window.FindName('ApplyButton')" fn)
  (write-line "$cancelButton = $window.FindName('CancelButton')" fn)
  (write-line "" fn)
  (write-line "$infoText.Text = \"対象ブロック: $($inputData.BlkCount)種類 / 内部図形: $($inputData.EntCount)個\"" fn)
  (write-line "" fn)
  (write-line "function Format-CurrentList ($arr) {" fn)
  (write-line "    if ($arr -and $arr.Count -gt 0) { return \"現在: \" + ($arr -join ', ') }" fn)
  (write-line "    return \"現在: (なし)\"" fn)
  (write-line "}" fn)
  (write-line "$currentLayersText.Text = Format-CurrentList $inputData.Layers" fn)
  (write-line "$currentLtypesText.Text = Format-CurrentList $inputData.Ltypes" fn)
  (write-line "$currentColorsText.Text = Format-CurrentList $inputData.Colors" fn)
  (write-line "$currentLwtsText.Text = Format-CurrentList $inputData.Lwts" fn)
  (write-line "" fn)
  (write-line "$noChange = '(変更しない)'" fn)
  (write-line "[void]$layerList.Items.Add($noChange)" fn)
  (write-line "if ($inputData.Layers -notcontains '0') { [void]$layerList.Items.Add('0') }" fn)
  (write-line "foreach ($l in $inputData.Layers) { [void]$layerList.Items.Add($l) }" fn)
  (write-line "$layerList.SelectedIndex = 0" fn)
  (write-line "" fn)
  (write-line "[void]$ltypeList.Items.Add($noChange)" fn)
  (write-line "if ($inputData.Ltypes -notcontains 'ByLayer') { [void]$ltypeList.Items.Add('ByLayer') }" fn)
  (write-line "if ($inputData.Ltypes -notcontains 'ByBlock') { [void]$ltypeList.Items.Add('ByBlock') }" fn)
  (write-line "foreach ($t in $inputData.Ltypes) { [void]$ltypeList.Items.Add($t) }" fn)
  (write-line "$ltypeList.SelectedIndex = 0" fn)
  (write-line "" fn)
  (write-line "$script:selectedColor = $null" fn)
  (write-line "$script:selectedLineweight = $null" fn)
  (write-line "" fn)
  (write-line "function Set-SelectedColor ($val, $label) {" fn)
  (write-line "    $script:selectedColor = $val" fn)
  (write-line "    $selectedColorText.Text = \"選択中の色: $label\"" fn)
  (write-line "}" fn)
  (write-line "Set-SelectedColor $null $noChange" fn)
  (write-line "" fn)
  (write-line "function Set-SelectedLineweight ($val, $label) {" fn)
  (write-line "    $script:selectedLineweight = $val" fn)
  (write-line "    $selectedLineweightText.Text = \"選択中の線の太さ: $label\"" fn)
  (write-line "}" fn)
  (write-line "Set-SelectedLineweight $null $noChange" fn)
  (write-line "" fn)
  (write-line "$chipStyle = $window.FindResource('ChipButton')" fn)
  (write-line "$swatchStyle = $window.FindResource('SwatchButton')" fn)
  (write-line "" fn)
  (write-line "$btnNone = New-Object System.Windows.Controls.Button" fn)
  (write-line "$btnNone.Style = $chipStyle" fn)
  (write-line "$btnNone.Content = $noChange" fn)
  (write-line "$btnNone.Add_Click({ Set-SelectedColor $null $noChange })" fn)
  (write-line "[void]$quickColorPanel.Children.Add($btnNone)" fn)
  (write-line "" fn)
  (write-line "$btnByLayer = New-Object System.Windows.Controls.Button" fn)
  (write-line "$btnByLayer.Style = $chipStyle" fn)
  (write-line "$btnByLayer.Content = 'ByLayer'" fn)
  (write-line "$btnByLayer.Add_Click({ Set-SelectedColor 'BYLAYER' 'ByLayer' })" fn)
  (write-line "[void]$quickColorPanel.Children.Add($btnByLayer)" fn)
  (write-line "" fn)
  (write-line "$btnByBlock = New-Object System.Windows.Controls.Button" fn)
  (write-line "$btnByBlock.Style = $chipStyle" fn)
  (write-line "$btnByBlock.Content = 'ByBlock'" fn)
  (write-line "$btnByBlock.Add_Click({ Set-SelectedColor 'BYBLOCK' 'ByBlock' })" fn)
  (write-line "[void]$quickColorPanel.Children.Add($btnByBlock)" fn)
  (write-line "" fn)
  (write-line "for ($i = 1; $i -le 255; $i++) {" fn)
  (write-line "    $rgb = Get-AciRgb $i" fn)
  (write-line "    $swatch = New-Object System.Windows.Controls.Button" fn)
  (write-line "    $swatch.Style = $swatchStyle" fn)
  (write-line "    $swatch.ToolTip = \"色番号 $i\"" fn)
  (write-line "    $swatch.Background = New-Object System.Windows.Media.SolidColorBrush([System.Windows.Media.Color]::FromRgb([byte]$rgb[0],[byte]$rgb[1],[byte]$rgb[2]))" fn)
  (write-line "    $idxCopy = $i" fn)
  (write-line "    $swatch.Add_Click({ Set-SelectedColor \"$idxCopy\" \"色番号 $idxCopy\" }.GetNewClosure())" fn)
  (write-line "    [void]$colorWrap.Children.Add($swatch)" fn)
  (write-line "}" fn)
  (write-line "" fn)
  (write-line "$lwNone = New-Object System.Windows.Controls.Button" fn)
  (write-line "$lwNone.Style = $chipStyle" fn)
  (write-line "$lwNone.Content = $noChange" fn)
  (write-line "$lwNone.Add_Click({ Set-SelectedLineweight $null $noChange })" fn)
  (write-line "[void]$lineweightPanel.Children.Add($lwNone)" fn)
  (write-line "" fn)
  (write-line "$lwByLayer = New-Object System.Windows.Controls.Button" fn)
  (write-line "$lwByLayer.Style = $chipStyle" fn)
  (write-line "$lwByLayer.Content = 'ByLayer'" fn)
  (write-line "$lwByLayer.Add_Click({ Set-SelectedLineweight 'BYLAYER' 'ByLayer' })" fn)
  (write-line "[void]$lineweightPanel.Children.Add($lwByLayer)" fn)
  (write-line "" fn)
  (write-line "$lwByBlock = New-Object System.Windows.Controls.Button" fn)
  (write-line "$lwByBlock.Style = $chipStyle" fn)
  (write-line "$lwByBlock.Content = 'ByBlock'" fn)
  (write-line "$lwByBlock.Add_Click({ Set-SelectedLineweight 'BYBLOCK' 'ByBlock' })" fn)
  (write-line "[void]$lineweightPanel.Children.Add($lwByBlock)" fn)
  (write-line "" fn)
  (write-line "$lwInput = New-Object System.Windows.Controls.TextBox" fn)
  (write-line "$lwInput.Width = 70" fn)
  (write-line "$lwInput.FontSize = 13" fn)
  (write-line "$lwInput.VerticalContentAlignment = 'Center'" fn)
  (write-line "$lwInput.Margin = [System.Windows.Thickness]'0,0,6,8'" fn)
  (write-line "$lwInput.ToolTip = 'mm単位で入力(例: 0.25)'" fn)
  (write-line "[void]$lineweightPanel.Children.Add($lwInput)" fn)
  (write-line "" fn)
  (write-line "$lwSetBtn = New-Object System.Windows.Controls.Button" fn)
  (write-line "$lwSetBtn.Style = $chipStyle" fn)
  (write-line "$lwSetBtn.Content = 'mmで設定'" fn)
  (write-line "$lwSetBtn.Add_Click({" fn)
  (write-line "    $mmVal = 0.0" fn)
  (write-line "    if ([double]::TryParse($lwInput.Text, [ref]$mmVal)) {" fn)
  (write-line "        $raw = [int][math]::Round($mmVal * 100)" fn)
  (write-line "        Set-SelectedLineweight \"$raw\" \"$($mmVal)mm\"" fn)
  (write-line "    } else {" fn)
  (write-line "        [System.Windows.MessageBox]::Show('数値を入力してください(例: 0.25)', '入力エラー') | Out-Null" fn)
  (write-line "    }" fn)
  (write-line "})" fn)
  (write-line "[void]$lineweightPanel.Children.Add($lwSetBtn)" fn)
  (write-line "" fn)
  (write-line "$window.Tag = 'CANCEL'" fn)
  (write-line "$applyButton.Add_Click({ $window.Tag = 'OK'; $window.Close() })" fn)
  (write-line "$cancelButton.Add_Click({ $window.Tag = 'CANCEL'; $window.Close() })" fn)
  (write-line "" fn)
  (write-line "[void]$window.ShowDialog()" fn)
  (write-line "" fn)
  (write-line "$result = @()" fn)
  (write-line "if ($window.Tag -eq 'OK') {" fn)
  (write-line "    $selLayer = $layerList.SelectedItem" fn)
  (write-line "    $selLtype = $ltypeList.SelectedItem" fn)
  (write-line "    if ($selLayer -and $selLayer -ne $noChange) { $result += \"LAYER=$selLayer\" }" fn)
  (write-line "    if ($selLtype -and $selLtype -ne $noChange) { $result += \"LTYPE=$selLtype\" }" fn)
  (write-line "    if ($script:selectedColor) { $result += \"COLOR=$($script:selectedColor)\" }" fn)
  (write-line "    if ($script:selectedLineweight) { $result += \"LWT=$($script:selectedLineweight)\" }" fn)
  (write-line "} else {" fn)
  (write-line "    $result += 'CANCEL'" fn)
  (write-line "}" fn)
  (write-line "" fn)
  (write-line "Set-Content -LiteralPath $OutputPath -Value $result -Encoding Default" fn)
  (close fn)
  (princ)
)

;; --- 選択エンティティから対象ブロック名(EffectiveName)一覧を得る -------
(defun qsbc-get-selected-block-names (ss / n i ent obj name names)
  (setq names '())
  (setq n (sslength ss))
  (setq i 0)
  (while (< i n)
    (setq ent (ssname ss i))
    (setq obj (vlax-ename->vla-object ent))
    (setq name (vla-get-EffectiveName obj))
    (if (not (member name names)) (setq names (cons name names)))
    (setq i (1+ i))
  )
  names
)

;; --- ブロック定義内の全エンティティを集める(recursive時は入れ子ブロックも展開) --
(defun qsbc-collect-entities (blkName recursive visited / doc blocks blk obj result nestedName blkResult)
  (if (member (strcase blkName) visited)
    '()
    (progn
      (setq visited (cons (strcase blkName) visited))
      (setq doc (vla-get-ActiveDocument (vlax-get-acad-object)))
      (setq blocks (vla-get-Blocks doc))
      (setq result '())
      (setq blkResult (vl-catch-all-apply 'vla-item (list blocks blkName)))
      (if (not (vl-catch-all-error-p blkResult))
        (progn
          (setq blk blkResult)
          (vlax-for obj blk
            (setq result (cons obj result))
            (if (and recursive (= (vla-get-ObjectName obj) "AcDbBlockReference"))
              (progn
                (setq nestedName (vla-get-EffectiveName obj))
                (setq result (append result (qsbc-collect-entities nestedName recursive visited)))
              )
            )
          )
        )
      )
      result
    )
  )
)

;; --- 色番号・線の太さを表示用文字列に変換 -------------------------------
(defun qsbc-color-to-str (val)
  (cond
    ((= val 0) "ByBlock")
    ((= val 256) "ByLayer")
    (T (itoa val))
  )
)
(defun qsbc-lwt-to-str (val)
  (cond
    ((= val -1) "ByLayer")
    ((= val -2) "ByBlock")
    ((= val -3) "既定")
    (T (strcat (rtos (/ val 100.0) 2 2) "mm"))
  )
)

;; --- 対象ブロック名すべてから、実体一覧・画層一覧・線種一覧・色一覧・線の太さ一覧を集計 --
(defun qsbc-gather-data (blockNames recursive / allEntities bn layers ltypes colors lwts lay lt col lw colStr lwStr obj)
  (setq allEntities '())
  (foreach bn blockNames
    (setq allEntities (append allEntities (qsbc-collect-entities bn recursive '())))
  )
  (setq layers '() ltypes '() colors '() lwts '())
  (foreach obj allEntities
    (setq lay (vla-get-Layer obj))
    (if (not (member lay layers)) (setq layers (cons lay layers)))
    (setq lt (vla-get-Linetype obj))
    (if (not (member lt ltypes)) (setq ltypes (cons lt ltypes)))
    (setq col (vla-get-Color obj))
    (setq colStr (qsbc-color-to-str col))
    (if (not (member colStr colors)) (setq colors (cons colStr colors)))
    (setq lw (vla-get-Lineweight obj))
    (setq lwStr (qsbc-lwt-to-str lw))
    (if (not (member lwStr lwts)) (setq lwts (cons lwStr lwts)))
  )
  (list allEntities (reverse layers) (reverse ltypes) (reverse colors) (reverse lwts))
)

;; --- 入力ファイル書き出し ---------------------------------------------
(defun qsbc-write-input-file (path layers ltypes colors lwts entCount blkCount / fn)
  (setq fn (open path "w"))
  (write-line "###LAYERS###" fn)
  (foreach l layers (write-line l fn))
  (write-line "###LTYPES###" fn)
  (foreach l ltypes (write-line l fn))
  (write-line "###COLORS###" fn)
  (foreach c colors (write-line c fn))
  (write-line "###LWTS###" fn)
  (foreach l lwts (write-line l fn))
  (write-line "###ENTCOUNT###" fn)
  (write-line (itoa entCount) fn)
  (write-line "###BLKCOUNT###" fn)
  (write-line (itoa blkCount) fn)
  (close fn)
  (princ)
)

;; --- 出力ファイル読み込み ---------------------------------------------
(defun qsbc-read-output-file (path / fn line result)
  (setq result '())
  (if (findfile path)
    (progn
      (setq fn (open path "r"))
      (while (setq line (read-line fn))
        (setq result (cons line result))
      )
      (close fn)
    )
  )
  (reverse result)
)

;; --- 収集したエンティティに画層・線種・色・線の太さを反映。戻り値は (成功数 失敗数) --
(defun qsbc-apply-changes (entities newLayer newLtype colorSpec lineweightSpec / okCnt errCnt obj res)
  (setq okCnt 0 errCnt 0)
  (foreach obj entities
    (setq res
      (vl-catch-all-apply
        '(lambda ()
           (if newLayer (vla-put-Layer obj newLayer))
           (if newLtype (vla-put-Linetype obj newLtype))
           (cond
             ((= colorSpec "BYLAYER") (vla-put-Color obj 256))
             ((= colorSpec "BYBLOCK") (vla-put-Color obj 0))
             (colorSpec (vla-put-Color obj (atoi colorSpec)))
           )
           (cond
             ((= lineweightSpec "BYLAYER") (vla-put-Lineweight obj -1))
             ((= lineweightSpec "BYBLOCK") (vla-put-Lineweight obj -2))
             (lineweightSpec (vla-put-Lineweight obj (atoi lineweightSpec)))
           )
         )
        nil
      )
    )
    (if (vl-catch-all-error-p res)
      (setq errCnt (1+ errCnt))
      (setq okCnt (1+ okCnt))
    )
  )
  (list okCnt errCnt)
)

;; --- メインコマンド ----------------------------------------------------
(defun c:qsbc ( / ss recursive blockNames blkCount data allEntities layers ltypes
                colors lwts entCount tmpDir inFile outFile ps1File outLines newLayer newLtype
                colorSpec lineweightSpec item eqPos key val applyResult)
  (setq ss (ssget '((0 . "INSERT"))))
  (if (not ss)
    (princ "\n編集対象のブロックが見つかりません。")
    (progn
      (setq recursive T)

      (setq blockNames (qsbc-get-selected-block-names ss))
      (setq blkCount (length blockNames))

      (setq data (qsbc-gather-data blockNames recursive))
      (setq allEntities (nth 0 data))
      (setq layers (nth 1 data))
      (setq ltypes (nth 2 data))
      (setq colors (nth 3 data))
      (setq lwts (nth 4 data))
      (setq entCount (length allEntities))

      (if (= entCount 0)
        (princ "\n対象となる図形が見つかりませんでした。")
        (progn
          (setq tmpDir (getenv "TEMP"))
          (setq inFile (strcat tmpDir "\\qsbc_input.txt"))
          (setq outFile (strcat tmpDir "\\qsbc_output.txt"))
          (setq ps1File (strcat tmpDir "\\qsbc_dialog.ps1"))

          (qsbc-write-input-file inFile layers ltypes colors lwts entCount blkCount)
          (qsbc-write-ps1-script ps1File)
          (qsbc-run-ps1 ps1File inFile outFile)

          (setq outLines (qsbc-read-output-file outFile))
          (setq newLayer nil newLtype nil colorSpec nil lineweightSpec nil)

          (if (and outLines (not (member "CANCEL" outLines)))
            (progn
              (foreach item outLines
                (setq eqPos (vl-string-search "=" item))
                (if eqPos
                  (progn
                    (setq key (substr item 1 eqPos))
                    (setq val (substr item (+ 2 eqPos)))
                    (cond
                      ((= key "LAYER") (setq newLayer val))
                      ((= key "LTYPE") (setq newLtype val))
                      ((= key "COLOR") (setq colorSpec val))
                      ((= key "LWT") (setq lineweightSpec val))
                    )
                  )
                )
              )
              (if (or newLayer newLtype colorSpec lineweightSpec)
                (progn
                  (setq applyResult (qsbc-apply-changes allEntities newLayer newLtype colorSpec lineweightSpec))
                  (command "_.REGENALL")
                  (princ (strcat "\n" (itoa (nth 0 applyResult)) "個の図形を更新しました。"))
                  (if (> (nth 1 applyResult) 0)
                    (princ (strcat "(" (itoa (nth 1 applyResult)) "個は変更できませんでした)"))
                  )
                )
                (princ "\n変更項目が選択されなかったため、何も更新しませんでした。")
              )
            )
            (princ "\nキャンセルされました。")
          )

          (if (findfile inFile) (vl-file-delete inFile))
          (if (findfile outFile) (vl-file-delete outFile))
          (if (findfile ps1File) (vl-file-delete ps1File))
        )
      )
    )
  )
  (princ)
)

(princ "\nQSBCコマンドをロードしました。ブロック内部の画層・線種・色・線の太さを一括変更するには 'QSBC' と入力してください。")
(princ)